### ISSUE TITLE
How can I add a background page?

### ISSUE THREAD

**Issue by RodolfoSilva** [marcbachmann/node-html-pdf#139]
I need add one background for all pages like:
<img src="http://www.estudio2002.com/imgs/trabalhos/PapelCartaA.jpg">
<img src="http://www.jmgraficaebrindes.com.br/wp-content/uploads/Papel-Timbrado_Colorido4x4_1.jpg">

How can I do that?

**Comment by RodolfoSilva** [comment]
Likely solution at my question:
```css

#pageHeader:after, 
.pageHeader:after {
  content: "";
  display: block;
  position:fixed;
  bottom:0;
  right:0;
  top:0;
  left:0;
  height: 842px;
  //- width: 595px;
  width: 100%;
  opacity: 0.5;
  background-image: url("background.png");
  background-repeat: no-repeat;
  background-position: center top;
  background-size: contain;
}
```

This works for me, probably it will help others who have the same problem.
