### ISSUE TITLE
Spacing in the table

### ISSUE THREAD

**Issue by LucasBurg** [marcbachmann/node-html-pdf#23]
I can not take this table spacing, Can you help me, please?

![table](https://cloud.githubusercontent.com/assets/8702152/6928180/c18e30b2-d7c8-11e4-95ed-3abe1eea87bf.PNG)

**Comment by marcbachmann** [comment]
Here's maybe a solution: http://stackoverflow.com/questions/16427903/remove-all-padding-and-margin-table-html-css

Please ask such questions on stackoverflow.
There's a large community that can answer html- & css- specific questions.

**Comment by marcbachmann** [comment]
Here's a css I've used.
```css

        table {
          border-collapse: collapse;
          border-spacing: 0;
          background: rgb(255, 255, 255);
          margin-bottom: 0.25em;
        }

        thead, tfoot {
          background: rgb(230, 230, 230);
          font-weight: 700;
        }

        thead td, tfoot td {
          padding: .4em .625em .4em;
          font-size: .875em;
          color: rgb(20, 20, 20);
          vertical-align: center;
        }

        tbody td {
          padding: .5em .625em .625em;
          font-size: .875em;
          color: rgb(50, 50, 50);
          text-align: left;
          vertical-align: top;
        }

        td .b {
          font-weight: 700;
        }

        td .d {
          margin: 5px 0 0 0;
        }


        tr {
          border-bottom: solid 1px rgb(200, 200, 200);
        }

        tr.highlight  {
          background: #808080;
        }
```
