### ISSUE TITLE
CSS overflow:hidden not supported?

### ISSUE THREAD

**Issue by Yutenko** [marcbachmann/node-html-pdf#30]
Hello,

is there any secret in using overflow:hidden or is it just not supported?
When positioning two divs absolute in a relative container and using overflow:hidden, the image beneath the other one is shown out of bounds.

Is it my fault or does your module don't support overflow:hidden property?

Greetings

**Comment by goodoldneon** [comment]
Almost 3 years too late, but I was able to get `overflow: hidden` to work by setting the height to 100%. If you also want to set `padding`, then also use `box-sizing: border-box`.

```css
.page {
	min-height: 100%;
	max-height: 100%;
	overflow: hidden;
	padding: 1em;
	box-sizing: border-box;
}
```
