### ISSUE TITLE
Size to PDF

### ISSUE THREAD

**Issue by LucasBurg** [marcbachmann/node-html-pdf#32]
What is the maximum size to PDF ?

**Comment by marcbachmann** [comment]
What size do you mean? Page count or Paper size? I actually have no Idea. I assume you'll get memory problems before you exceed the size limit of phantomjs. I wouldn't create pages that are larger than 40pages.

**Comment by LucasBurg** [comment]
Thanks for the feedback, It is the size of the file. really had a memory problem, most managed to solve and I'm generating more than 300 pages with text and small images. thanks for developing this project!

**Comment by senica** [comment]
Is there anyway to stream the process? I have a very large pdf I'm trying to generate. the html file is 111MB. I set the timeout to 30 minutes :) but it just always dies.  Any way to circumvent this?
```
pdf.create(html, {
                format: 'Letter'
                orientation: 'portrait'
                border:
                  top: '.5in'
                  right: '.5in'
                  bottom: '.5in'
                  left: '.5in'
                type: 'pdf'
                timeout: 600000 # 10 minutes
                filename: file_pdf
              }).toFile
```
