### ISSUE TITLE
Not rendering web fonts

### ISSUE THREAD

**Issue by dooburt** [marcbachmann/node-html-pdf#9]
Hi there,
I'm having no luck getting html-pdf to render webfonts that are included within the HTML itself.  For example, the fonts are included within a `<style>` block on the HTML:-

``` css
@font-face {
                font-family: 'Raleway';
                src: url('/static/fonts/raleway/raleway-regular-webfont.eot');
                src: url('/static/fonts/raleway/raleway-regular-webfont.eot?#iefix') format('embedded-opentype'),
                     url('/static/fonts/raleway/raleway-regular-webfont.woff') format('woff'),
                     url('/static/fonts/raleway/raleway-regular-webfont.ttf') format('truetype'),
                     url('/static/fonts/raleway/raleway-regular-webfont.svg#ralewayregular') format('svg');
                font-weight: normal;
                font-style: normal;

            }
            body 
            {
                font-family: 'Raleway';
                font-size: 14px;
            }
```

The fonts are rendered when visiting the template HTML manually. But when html-pdf renders the page to PDF, it is output in Helvetica throughout. My assumption is this is a race condition, with html-pdf rendering before the fonts are called and rendered -- but I maybe simplifying it.  Can you offer any steer as to how this can be achieved?

Many thanks
